//GLOBAL ACTIONS
export const CHANGE_STATE = "CHANGE_STATE";
export const RESET_STORE = "RESET_STORE";

//TICKET ACTIONS
export const LIST_TICKETS = "LIST_TICKETS";
export const SAVE_TICKET = "SAVE_TICKET";
export const SET_TICKET = "SET_TICKET";
export const UPDATE_TICKET = "UPDATE_TICKET";
export const DELETE_TICKET = "DELETE_TICKET";
export const UPDATE_ATENTION = "UPDATE_ATENTION";

//ATENTION ACTIONS
export const LIST_ATENTION = "LIST_ATENTION";
export const SET_IDTICKET = "SET_IDTICKET";
export const SAVE_ATENTION = "SAVE_ATENTION";
export const HISTORIAL_ATENTION = "HISTORIAL_ATENTION";
